import CppFormalization.Cpp4.Typing.Judgment.Surface.Block
import CppFormalization.Cpp4.Core.Program

/-!
# CppFormalization.Cpp4.Typing.Judgment.Surface.Function

Surface function-body typing certificates.
-/

namespace Cpp4

namespace FunctionSig

/-- Ordinary-name environment entry induced by one function parameter. -/
def paramEntry (p : Param) : Ident × DeclInfo :=
  match p.passing with
  | .byValue => (p.name, .object p.ty)
  | .byRef => (p.name, .ref p.ty)

/-- Initial type environment for a function body. -/
def bodyEnv (sig : FunctionSig) : TypeEnv :=
  TypeEnv.bindMany TypeEnv.empty (sig.params.map paramEntry)

end FunctionSig

/-- A typed surface function body. -/
structure FunctionBodyTyping (sig : FunctionSig) (body : StmtBlock) : Type where
  bodyTyping : SurfaceBlockTyping sig.bodyEnv (ControlContext.enterFunction sig.ret) body
  formation : Prop
  evidence : formation

namespace FunctionBodyTyping

/-- Build a function-body certificate from a typed surface block. -/
def ofBlock {sig : FunctionSig} {body : StmtBlock}
    (hBody : SurfaceBlockTyping sig.bodyEnv (ControlContext.enterFunction sig.ret) body) :
    FunctionBodyTyping sig body where
  bodyTyping := hBody
  formation := hBody.formation
  evidence := hBody.evidence

/-- Demand generated by a typed function body. -/
def demand {sig : FunctionSig} {body : StmtBlock}
    (h : FunctionBodyTyping sig body) : SurfaceBlockDemand :=
  h.bodyTyping.demand

end FunctionBodyTyping

/-- A typed internal function definition. -/
structure InternalFunctionTyping (d : InternalFunctionDef) : Type where
  bodyTyping : FunctionBodyTyping d.sig d.body
  formation : Prop
  evidence : formation

namespace InternalFunctionTyping

/-- Build an internal-function certificate from its typed body. -/
def mkBody {d : InternalFunctionDef}
    (hBody : FunctionBodyTyping d.sig d.body) : InternalFunctionTyping d where
  bodyTyping := hBody
  formation := hBody.formation
  evidence := hBody.evidence

end InternalFunctionTyping

end Cpp4
