import CppFormalization.Cpp2.Static.Env.All
import CppFormalization.Cpp2.Static.Facts.All
import CppFormalization.Cpp2.Static.Pure.All
import CppFormalization.Cpp2.Static.SeqStatic.All
import CppFormalization.Cpp2.Static.StructuralAdmission.All
import CppFormalization.Cpp2.Static.Typing.All
import CppFormalization.Cpp2.Static.NoDeclareObj
import CppFormalization.Cpp2.Static.ScopeDiscipline
import CppFormalization.Cpp2.Static.WellFormed
