import CppFormalization.Cpp2.Legacy.ClosureInternal.BlockBodyFunctionClosureLite
import CppFormalization.Cpp2.Legacy.ClosureInternal.BlockFunctionBodyClosureLite_recursor
import CppFormalization.Cpp2.Legacy.ClosureInternal.BodyBoundaryLiteCompatibility
import CppFormalization.Cpp2.Legacy.ClosureInternal.FunctionBodyClosureConcreteRefined
import CppFormalization.Cpp2.Legacy.ClosureInternal.SeqFunctionBodyClosureLite
import CppFormalization.Cpp2.Legacy.ClosureInternal.SmallReusableWrappersCI
import CppFormalization.Cpp2.Legacy.ClosureInternal.StmtAbruptCompatibility
import CppFormalization.Cpp2.Legacy.ClosureInternal.StmtControlCompatibility
