-- import CppFormalization.Cpp2.Closure.Internal.ArchitectureRoadmap
import CppFormalization.Cpp2.Closure.Internal.AssignHeadResidualTransportTheorems
import CppFormalization.Cpp2.Closure.Internal.AssignHeadPushScopeBridges
import CppFormalization.Cpp2.Closure.Internal.AssignHeadWhileTransportCompat
import CppFormalization.Cpp2.Closure.Internal.AssignHeadWhileTransportTheorems
import CppFormalization.Cpp2.Closure.Internal.AssignTransportKernel
import CppFormalization.Cpp2.Closure.Internal.BlockBodyClosureCI
import CppFormalization.Cpp2.Closure.Internal.BlockBodyClosureConcrete
import CppFormalization.Cpp2.Closure.Internal.BlockBodyFunctionClosureLite
import CppFormalization.Cpp2.Closure.Internal.BlockBodyNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.BlockFunctionBodyClosureLite_recursor
import CppFormalization.Cpp2.Closure.Internal.BlockNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.BodyBoundaryLiteCompatibility
import CppFormalization.Cpp2.Closure.Internal.ConditionReplayKernel
import CppFormalization.Cpp2.Closure.Internal.ConditionalNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.CurrentShellCI
import CppFormalization.Cpp2.Closure.Internal.DerefAssignLocalInterfaces
import CppFormalization.Cpp2.Closure.Internal.DerefAssignTransportKernel
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyCaseDriverCI
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyCaseSplitCI
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyClosure
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyClosureCI
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyClosureConcrete
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyClosureConcreteRefined
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyPrimitiveClosureCI
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyReplayStablePrimitiveWhileFacts
import CppFormalization.Cpp2.Closure.Internal.InternalClosureRoadmap
import CppFormalization.Cpp2.Closure.Internal.InternalClosureRoadmapCI
import CppFormalization.Cpp2.Closure.Internal.InternalClosureRoadmapConcrete
import CppFormalization.Cpp2.Closure.Internal.LoopBodyFunctionClosureCI
import CppFormalization.Cpp2.Closure.Internal.LoopReentryKernelCI
import CppFormalization.Cpp2.Closure.Internal.NormalPathTypingBridge
import CppFormalization.Cpp2.Closure.Internal.PrimitiveStmtNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.PtrExprAssignTransportKernel
import CppFormalization.Cpp2.Closure.Internal.ReadinessBoundaryConcrete
import CppFormalization.Cpp2.Closure.Internal.ReadinessReplayPrimitive
import CppFormalization.Cpp2.Closure.Internal.ReadinessResidualBoundary
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormal
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalCore
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalEnvExtending
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalEnvExtendingNames
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalEnvExtendingOldNames
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalEnvPreserving
import CppFormalization.Cpp2.Closure.Internal.ReadinessTransportNormalStableFragment
import CppFormalization.Cpp2.Closure.Internal.ResidualTransportStableFragment
import CppFormalization.Cpp2.Closure.Internal.ResidualTransportableDeclarationsFragment
import CppFormalization.Cpp2.Closure.Internal.ResidualTransportStrongThinSeparatedDeclarationsFragment
import CppFormalization.Cpp2.Closure.Internal.ResidualTransportStrongThinSeparatedFragment
import CppFormalization.Cpp2.Closure.Internal.SeqFunctionBodyClosureLite
import CppFormalization.Cpp2.Closure.Internal.SequentialNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.SequentialStmtNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.StmtAbruptCompatibility
import CppFormalization.Cpp2.Closure.Internal.StmtControlCompatibility
import CppFormalization.Cpp2.Closure.Internal.StmtControlKernel
import CppFormalization.Cpp2.Closure.Internal.StmtControlPreservation
import CppFormalization.Cpp2.Closure.Internal.StmtNormalCompatCases
import CppFormalization.Cpp2.Closure.Internal.StrongThinSeparatedCondReplay
import CppFormalization.Cpp2.Closure.Internal.StrongThinSeparatedDerefTheorems
import CppFormalization.Cpp2.Closure.Internal.ThinSeparatedDerefAssignKernel
import CppFormalization.Cpp2.Closure.Internal.Transport.All
import CppFormalization.Cpp2.Closure.Internal.TypingCINormalExclusion
import CppFormalization.Cpp2.Closure.Internal.TypingCISeparation
import CppFormalization.Cpp2.Closure.Internal.WhileBodyClassCI
import CppFormalization.Cpp2.Closure.Internal.WhileDecompositionFacts
import CppFormalization.Cpp2.Closure.Internal.WhileFunctionClosureKernelCI
import CppFormalization.Cpp2.Closure.Internal.WhileNormalPreservation
import CppFormalization.Cpp2.Closure.Internal.WhileReentryKernelFacts
import CppFormalization.Cpp2.Closure.Internal.WhileReentryReadyKernelCI
import CppFormalization.Cpp2.Closure.Internal.WhileReplayStablePrimitiveFacts
import CppFormalization.Cpp2.Closure.Internal.WhileStrongThinSeparatedAssignFacts

/-!
# Closure.Internal.All

Build-coverage aggregate for `Closure.Internal`.

`ArchitectureRoadmap` remains intentionally excluded as a roadmap/debt ledger.
`Transport.All` is a nested aggregate at `Closure/Internal/Transport/All.lean`.
-/
