import CppFormalization.Cpp2.Closure.Foundation.BodyAdequacyWitnessCI
import CppFormalization.Cpp2.Closure.Internal.FunctionBodyCaseSplitCI

namespace Cpp

/-!
# Closure.Internal.IteBranchAdequacyAssetsCI

Secondary assets for deriving slot-aware `ite` branch adequacy from ordinary
branch-local `BodyAdequacyCI`, and from the new witness-producing adequacy
provider layer.

The key distinction is that the adequacy evidence must be for the profile
generated by the branch-local slot payload `S.toProfile`.
-/

namespace IteBranchProfileSlotPayloadCI

/--
Type-level inversion of a normal summary equality for a slot-generated branch
profile.

This is purely structural `Option.map` inversion; it is not a semantic adequacy
theorem.
-/
def normalSlotWitness_of_toProfile_normalOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .normalK Γ st Δ}}
    (h : S.toProfile.summary.normalOut = some out) :
    { n : IteBranchNormalSlotCI Γ st //
      S.normalSlot = some n ∧ IteBranchNormalSlotCI.out n = out } := by
  cases hslot : S.normalSlot with
  | none =>
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
  | some n =>
      refine ⟨n, ?_⟩
      constructor
      · rfl
      · simpa [IteBranchProfileSlotPayloadCI.toProfile, hslot] using h

/--
Invert a normal summary equality for a slot-generated branch profile.

This is the proof-only projection of
`normalSlotWitness_of_toProfile_normalOut_eq_some`.
-/
theorem normalSlot_of_toProfile_normalOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .normalK Γ st Δ}}
    (h : S.toProfile.summary.normalOut = some out) :
    ∃ n : IteBranchNormalSlotCI Γ st,
      S.normalSlot = some n ∧ IteBranchNormalSlotCI.out n = out := by
  let w := S.normalSlotWitness_of_toProfile_normalOut_eq_some h
  exact ⟨w.val, w.property⟩

/--
Type-level inversion of a return summary equality for a slot-generated branch
profile.
-/
def returnSlotWitness_of_toProfile_returnOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .returnK Γ st Δ}}
    (h : S.toProfile.summary.returnOut = some out) :
    { r : IteBranchReturnSlotCI Γ st //
      S.returnSlot = some r ∧ IteBranchReturnSlotCI.out r = out } := by
  cases hslot : S.returnSlot with
  | none =>
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
  | some r =>
      refine ⟨r, ?_⟩
      constructor
      · rfl
      · simpa [IteBranchProfileSlotPayloadCI.toProfile, hslot] using h

/--
Invert a return summary equality for a slot-generated branch profile.

This is the proof-only projection of
`returnSlotWitness_of_toProfile_returnOut_eq_some`.
-/
theorem returnSlot_of_toProfile_returnOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .returnK Γ st Δ}}
    (h : S.toProfile.summary.returnOut = some out) :
    ∃ r : IteBranchReturnSlotCI Γ st,
      S.returnSlot = some r ∧ IteBranchReturnSlotCI.out r = out := by
  let w := S.returnSlotWitness_of_toProfile_returnOut_eq_some h
  exact ⟨w.val, w.property⟩

end IteBranchProfileSlotPayloadCI

namespace IteBranchSlotAdequacySupportCI

/--
Convert ordinary branch-local adequacy for `S.toProfile` into slot-aware
adequacy support for `S`.

This remains the classical bridge from proof-only adequacy to a Type-level slot
support package.  The `ofBodyAdequacyWitness` route below is the preferred route
when witness-producing adequacy is available.
-/
noncomputable def ofBodyAdequacy
    {Γ : TypeEnv} {σ : State} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    (A : BodyAdequacyCI Γ σ st S.toProfile) :
    IteBranchSlotAdequacySupportCI Γ σ st S :=
  { normalDecision := by
      intro σ' hstep
      let houtEx := A.normalSound hstep
      let out := Classical.choose houtEx
      have hout : S.toProfile.summary.normalOut = some out :=
        Classical.choose_spec houtEx
      let w := S.normalSlotWitness_of_toProfile_normalOut_eq_some hout
      exact
        { Delta := w.val.Δ
          hty := w.val.hty
          hslot := w.property.1 }
    returnDecision := by
      intro rv σ' hstep
      let houtEx := A.returnSound hstep
      let out := Classical.choose houtEx
      have hout : S.toProfile.summary.returnOut = some out :=
        Classical.choose_spec houtEx
      let w := S.returnSlotWitness_of_toProfile_returnOut_eq_some hout
      exact
        { Delta := w.val.Δ
          hty := w.val.hty
          hslot := w.property.1 } }

/--
Convert witness-producing branch-local adequacy for `S.toProfile` into
slot-aware adequacy support for `S`.

Unlike `ofBodyAdequacy`, this route does not need to choose the profile output
from a `Prop`-level existential; the profile witness is supplied directly by the
witness-producing adequacy layer.
-/
def ofBodyAdequacyWitness
    {Γ : TypeEnv} {σ : State} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    (A : BodyAdequacyWitnessCI Γ σ st S.toProfile) :
    IteBranchSlotAdequacySupportCI Γ σ st S :=
  { normalDecision := by
      intro σ' hstep
      let hout := A.normalWitness hstep
      let w := S.normalSlotWitness_of_toProfile_normalOut_eq_some hout.property
      exact
        { Delta := w.val.Δ
          hty := w.val.hty
          hslot := w.property.1 }
    returnDecision := by
      intro rv σ' hstep
      let hout := A.returnWitness hstep
      let w := S.returnSlotWitness_of_toProfile_returnOut_eq_some hout.property
      exact
        { Delta := w.val.Δ
          hty := w.val.hty
          hslot := w.property.1 } }

end IteBranchSlotAdequacySupportCI

end Cpp
