import CppFormalization.Cpp2.Closure.Internal.FunctionBodyCaseSplitCI

namespace Cpp

/-!
# Closure.Internal.IteBranchAdequacyAssetsCI

Secondary assets for deriving slot-aware `ite` branch adequacy from ordinary
branch-local `BodyAdequacyCI`.

The key distinction is that the `BodyAdequacyCI` must be for the profile
generated by the branch-local slot payload `S.toProfile`.
-/

namespace IteBranchProfileSlotPayloadCI

/--
Invert a normal summary equality for a slot-generated branch profile.

This is purely structural `Option.map` inversion; it is not a semantic
adequacy theorem.
-/
theorem normalSlot_of_toProfile_normalOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .normalK Γ st Δ}}
    (h : S.toProfile.summary.normalOut = some out) :
    ∃ n : IteBranchNormalSlotCI Γ st,
      S.normalSlot = some n ∧ IteBranchNormalSlotCI.out n = out := by
  cases hslot : S.normalSlot with
  | none =>
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
  | some n =>
      refine ⟨n, rfl, ?_⟩
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
      exact h

/--
Invert a return summary equality for a slot-generated branch profile.
-/
theorem returnSlot_of_toProfile_returnOut_eq_some
    {Γ : TypeEnv} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    {out : {Δ : TypeEnv // HasTypeStmtCI .returnK Γ st Δ}}
    (h : S.toProfile.summary.returnOut = some out) :
    ∃ r : IteBranchReturnSlotCI Γ st,
      S.returnSlot = some r ∧ IteBranchReturnSlotCI.out r = out := by
  cases hslot : S.returnSlot with
  | none =>
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
  | some r =>
      refine ⟨r, rfl, ?_⟩
      simp [IteBranchProfileSlotPayloadCI.toProfile, hslot] at h
      exact h

end IteBranchProfileSlotPayloadCI

namespace IteBranchSlotAdequacySupportCI

/--
Convert ordinary branch-local adequacy for `S.toProfile` into slot-aware
adequacy support for `S`.

This is the bridge that should eventually replace the four per-branch
runtime-decision axioms once the then/else branch profile payload is known to
come from an actual branch closure boundary.
-/
noncomputable def ofBodyAdequacy
    {Γ : TypeEnv} {σ : State} {st : CppStmt}
    (S : IteBranchProfileSlotPayloadCI Γ st)
    (A : BodyAdequacyCI Γ σ st S.toProfile) :
    IteBranchSlotAdequacySupportCI Γ σ st S :=
  { normalDecision := by
      intro σ' hstep

      let houtEx :=
        A.normalSound hstep
      let out :=
        Classical.choose houtEx
      have hout :
          S.toProfile.summary.normalOut = some out :=
        Classical.choose_spec houtEx

      let hnEx :=
        S.normalSlot_of_toProfile_normalOut_eq_some hout
      let n :=
        Classical.choose hnEx
      have hn :
          S.normalSlot = some n ∧ IteBranchNormalSlotCI.out n = out :=
        Classical.choose_spec hnEx

      exact
        { Delta := n.Δ
          hty := n.hty
          hslot := hn.1 }

    returnDecision := by
      intro rv σ' hstep

      let houtEx :=
        A.returnSound hstep
      let out :=
        Classical.choose houtEx
      have hout :
          S.toProfile.summary.returnOut = some out :=
        Classical.choose_spec houtEx

      let hrEx :=
        S.returnSlot_of_toProfile_returnOut_eq_some hout
      let r :=
        Classical.choose hrEx
      have hr :
          S.returnSlot = some r ∧ IteBranchReturnSlotCI.out r = out :=
        Classical.choose_spec hrEx

      exact
        { Delta := r.Δ
          hty := r.hty
          hslot := hr.1 } }

end IteBranchSlotAdequacySupportCI

end Cpp
