import CppFormalization.Cpp2.Closure.Foundation.BlockBodyDynamicBoundaryLite
import CppFormalization.Cpp2.Closure.Foundation.BodyAdequacyCI
import CppFormalization.Cpp2.Closure.Foundation.BodyAdequacyLite
import CppFormalization.Cpp2.Closure.Foundation.BodyBoundaryCI
import CppFormalization.Cpp2.Closure.Foundation.BodyBoundaryCoherence
import CppFormalization.Cpp2.Closure.Foundation.BodyBoundaryCompatibility
import CppFormalization.Cpp2.Closure.Foundation.BodyClosureBoundaryCI
import CppFormalization.Cpp2.Closure.Foundation.BodyClosureBoundaryLite
import CppFormalization.Cpp2.Closure.Foundation.BodyDynamicBoundary
import CppFormalization.Cpp2.Closure.Foundation.BodyStaticBoundaryCI
import CppFormalization.Cpp2.Static.Pure.BodyStructuralBoundary
import CppFormalization.Cpp2.Static.Pure.BodyStructuralBoundaryLite
import CppFormalization.Cpp2.Closure.Foundation.CoreBigStepFragment
import CppFormalization.Cpp2.Closure.Foundation.DeclareReadyStrongBridge
import CppFormalization.Cpp2.Closure.Foundation.LoopBodyBoundaryCI
import CppFormalization.Cpp2.Closure.Foundation.LoopBodyBoundaryCompatibility
import CppFormalization.Cpp2.Closure.Foundation.Readiness
import CppFormalization.Cpp2.Closure.Foundation.ReadinessInversions
import CppFormalization.Cpp2.Closure.Foundation.ReadinessObjectDeclBridge
import CppFormalization.Cpp2.Closure.Foundation.ReadinessSemanticsBridge
import CppFormalization.Cpp2.Closure.Foundation.StateBoundary
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcrete
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteDeclRealization
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteDeclTransport
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteExactnessTransport
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteFullAssembly
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteOwnershipAssembly
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteOwnershipTransport
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcretePreservation
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteReadyTransport
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteRecomputedCursor
import CppFormalization.Cpp2.Closure.Foundation.StateInvariantConcreteStrengthening
import CppFormalization.Cpp2.Static.Pure.WellFormedFromTyping
import CppFormalization.Cpp2.Closure.Foundation.WhileEntryBoundaryCI

/-!
# CppFormalization.Cpp2.Closure.Foundation.All

Exhaustive aggregate for this directory.

This file imports every Lean file directly under this directory, except itself,
and every immediate child directory through that child directory's `All.lean`.
-/
