import CppFormalization.Cpp4.Semantics.Kernel.Expr
import CppFormalization.Cpp4.Resource.Effect.Core

/-!
# CppFormalization.Cpp4.Semantics.Effect.Expr

Effect-carrying wrappers for finite expression/place/call-argument kernel steps.

`Resource.Effect` defines the low-level effect vocabulary.  This file does not
redefine it; it packages kernel execution together with an explicit effect trace
so later realization layers can refine the trace generated by each rule.
-/

namespace Cpp4

/-- A finite place-evaluation step with an explicit resource-effect trace. -/
structure BigStepPlaceWithEffect
    (χ : KernelContext) (σ : State) (p : PlaceExpr) (a : Address) (σ' : State) : Type where
  step : BigStepPlace χ σ p a σ'
  trace : EffectTrace σ σ'

/-- A finite value-evaluation step with an explicit resource-effect trace. -/
structure BigStepValueWithEffect
    (χ : KernelContext) (σ : State) (e : ValExpr) (v : Value) (σ' : State) : Type where
  step : BigStepValue χ σ e v σ'
  trace : EffectTrace σ σ'

/-- A finite call-argument-list evaluation step with an explicit effect trace. -/
structure BigStepCallArgsWithEffect
    (χ : KernelContext) (σ : State) (args : CallArgs) (values : List Value) (σ' : State) : Type where
  step : BigStepCallArgs χ σ args values σ'
  trace : EffectTrace σ σ'

namespace BigStepPlaceWithEffect

/-- Attach an already chosen resource-effect trace to a place step. -/
def attach {χ : KernelContext} {σ σ' : State} {p : PlaceExpr} {a : Address}
    (step : BigStepPlace χ σ p a σ') (effect : ResourceEffect) :
    BigStepPlaceWithEffect χ σ p a σ' where
  step := step
  trace := { effect := effect }

/-- Forget the resource-effect trace. -/
def forget {χ : KernelContext} {σ σ' : State} {p : PlaceExpr} {a : Address}
    (h : BigStepPlaceWithEffect χ σ p a σ') : BigStepPlace χ σ p a σ' :=
  h.step

end BigStepPlaceWithEffect

namespace BigStepValueWithEffect

/-- Attach an already chosen resource-effect trace to a value step. -/
def attach {χ : KernelContext} {σ σ' : State} {e : ValExpr} {v : Value}
    (step : BigStepValue χ σ e v σ') (effect : ResourceEffect) :
    BigStepValueWithEffect χ σ e v σ' where
  step := step
  trace := { effect := effect }

/-- Forget the resource-effect trace. -/
def forget {χ : KernelContext} {σ σ' : State} {e : ValExpr} {v : Value}
    (h : BigStepValueWithEffect χ σ e v σ') : BigStepValue χ σ e v σ' :=
  h.step

end BigStepValueWithEffect

namespace BigStepCallArgsWithEffect

/-- Attach an already chosen resource-effect trace to a call-argument-list step. -/
def attach {χ : KernelContext} {σ σ' : State} {args : CallArgs} {values : List Value}
    (step : BigStepCallArgs χ σ args values σ') (effect : ResourceEffect) :
    BigStepCallArgsWithEffect χ σ args values σ' where
  step := step
  trace := { effect := effect }

/-- Forget the resource-effect trace. -/
def forget {χ : KernelContext} {σ σ' : State} {args : CallArgs} {values : List Value}
    (h : BigStepCallArgsWithEffect χ σ args values σ') :
    BigStepCallArgs χ σ args values σ' :=
  h.step

end BigStepCallArgsWithEffect

end Cpp4
