import CppFormalization.Cpp4.Typing.Micro.Expr
import CppFormalization.Cpp4.Resource.Demand.Call

/-!
# CppFormalization.Cpp4.Typing.Micro.CallArgs

Micro typing for function-call arguments and callable expressions.
-/

namespace Cpp4

/-- Compatibility between a typed argument expression and one declared parameter.
The initial Cpp4 fragment keeps by-value and by-reference compatibility at the
same type-equality surface; later layers can refine this with value category and
lifetime constraints. -/
def ArgCompatible (argTy : CppType) (param : Param) : Prop :=
  argTy = param.ty

/-- Syntax-directed typing for call argument lists against a function signature's
parameter list. -/
inductive CallArgsTyping (Γ : TypeEnv) : CallArgs → List Param → Type where
  | nil : CallArgsTyping Γ .nil []
  | cons {e : ValExpr} {es : CallArgs} {p : Param} {ps : List Param}
      (head : ExprTyping Γ e)
      (compatible : ArgCompatible head.ty p)
      (tail : CallArgsTyping Γ es ps) :
      CallArgsTyping Γ (.cons e es) (p :: ps)

namespace CallArgsTyping

/-- Expression-demand fragments generated by typed call arguments. -/
def exprDemands {Γ : TypeEnv} {args : CallArgs} {params : List Param} :
    CallArgsTyping Γ args params → List ExprDemand
  | .nil => []
  | .cons head _ tail => head.demand :: exprDemands tail

/-- Number of typed arguments. -/
def arity {Γ : TypeEnv} {args : CallArgs} {params : List Param} :
    CallArgsTyping Γ args params → Nat
  | .nil => 0
  | .cons _ _ tail => tail.arity + 1

end CallArgsTyping

/-- Micro typing certificate for a callable application. -/
structure CallTyping
    (Γ : TypeEnv) (Φ : FunctionEnv) (f : FunctionName) (args : CallArgs) : Type where
  decl : CallableDecl
  lookup : Φ.lookup f = some decl
  argsTyping : CallArgsTyping Γ args decl.sig.params

namespace CallTyping

/-- Demand generated by a typed call. -/
def demand {Γ : TypeEnv} {Φ : FunctionEnv} {f : FunctionName} {args : CallArgs}
    (h : CallTyping Γ Φ f args) : CallDemand :=
  CallDemand.withArgs f h.argsTyping.exprDemands

/-- Return type of a typed call. -/
def retTy {Γ : TypeEnv} {Φ : FunctionEnv} {f : FunctionName} {args : CallArgs}
    (h : CallTyping Γ Φ f args) : CppType :=
  h.decl.sig.ret

end CallTyping

namespace ExprTyping

/-- Turn a typed callable application into a typed value expression. -/
def call {Γ : TypeEnv} {Φ : FunctionEnv} {f : FunctionName} {args : CallArgs}
    (h : CallTyping Γ Φ f args) : ExprTyping Γ (.call f args) where
  ty := h.retTy
  demand := ExprDemand.ofDemandSet h.demand.demands
  formation := True
  evidence := trivial

end ExprTyping

end Cpp4
