import CppFormalization.Cpp4.Resource.Demand.Atom

/-!
# CppFormalization.Cpp4.Typing.Micro.Control

Micro typing for C++ control-transfer atoms.

Reserved words are lexical syntax.  This layer records the C++ placement rule:
`break`, `continue`, and `return` are only typable under a compatible
`ControlContext`, and the resulting typed atom exposes the matching
`AtomDemand`.
-/

namespace Cpp4

/-- Micro typing for a `break` jump. -/
structure BreakTyping (κ : ControlContext) : Type where
  allowed : BreakAllowed κ

/-- Micro typing for a `continue` jump. -/
structure ContinueTyping (κ : ControlContext) : Type where
  allowed : ContinueAllowed κ

/-- Micro typing for a `return;` jump.  The enclosing function return channel is
kept explicit because later C++ fragments may refine void-return compatibility. -/
structure ReturnVoidTyping (κ : ControlContext) : Type where
  retTy : CppType
  allowed : ReturnAllowed κ retTy

/-- Micro typing for a `return e;` jump after the returned expression has already
been typed. -/
structure ReturnValueTyping (κ : ControlContext) (e : ValExpr) : Type where
  retTy : CppType
  valueTy : CppType
  allowed : ReturnAllowed κ retTy
  valueMatchesReturn : valueTy = retTy

/-- Micro typing for non-local control-transfer syntax. -/
inductive JumpTyping (κ : ControlContext) : CppJump → Type where
  | breakStmt (h : BreakTyping κ) :
      JumpTyping κ .breakStmt
  | continueStmt (h : ContinueTyping κ) :
      JumpTyping κ .continueStmt
  | returnVoid (h : ReturnVoidTyping κ) :
      JumpTyping κ (.returnStmt .void)
  | returnValue {e : ValExpr} (h : ReturnValueTyping κ e) :
      JumpTyping κ (.returnStmt (.value e))

namespace JumpTyping

/-- The resource demand generated by a typed control-transfer atom. -/
def demand {κ : ControlContext} {j : CppJump} : JumpTyping κ j → AtomDemand
  | .breakStmt _ => AtomDemand.jump .breakStmt
  | .continueStmt _ => AtomDemand.jump .continueStmt
  | .returnVoid h => AtomDemand.returnAllowed h.retTy
  | .returnValue h => AtomDemand.returnAllowed h.retTy

/-- View a typed jump as a typed control atom demand. -/
def atomDemand {κ : ControlContext} {j : CppJump}
    (h : JumpTyping κ j) : AtomDemand :=
  h.demand

end JumpTyping

namespace ControlContext

/-- Enter the body of a switch arm.  `break` becomes valid, while `continue` is
not introduced by the switch itself. -/
def switchBody (κ : ControlContext) : ControlContext :=
  enterSwitch κ

/-- Enter a loop body.  Both `break` and `continue` become valid. -/
def loopBody (κ : ControlContext) : ControlContext :=
  enterLoop κ

/-- Enter the iteration expression of a `for` loop.  It is evaluated while still
inside the loop's control context. -/
def forIteration (κ : ControlContext) : ControlContext :=
  enterLoop κ

end ControlContext

end Cpp4
