import CppFormalization.Cpp4.Typing.Micro.CallArgs
import CppFormalization.Cpp4.Typing.Micro.Control
import CppFormalization.Cpp4.Typing.Micro.EnvEffect

/-!
# CppFormalization.Cpp4.Typing.Micro.Decl

Micro typing for declarations, expression statements, assignments, and primitive
control atoms.
-/

namespace Cpp4

/-- Initializer typing against an expected object type. -/
inductive InitTyping (Γ : TypeEnv) : CppInit → CppType → Type where
  | noInit {τ : CppType} : InitTyping Γ .noInit τ
  | value {e : ValExpr} {τ : CppType}
      (exprTyping : ExprTyping Γ e)
      (compatible : exprTyping.ty = τ) :
      InitTyping Γ (.value e) τ

namespace InitTyping

/-- Demand generated by an initializer. -/
def demand {Γ : TypeEnv} {init : CppInit} {τ : CppType} :
    InitTyping Γ init τ → ExprDemand
  | .noInit => ExprDemand.empty
  | .value exprTyping _ => exprTyping.demand

end InitTyping

/-- Micro typing certificate for a declaration. -/
structure DeclTyping (Γ : TypeEnv) (d : CppDecl) : Type where
  target : TypeEnv
  envEffect : TypeEnvEffect Γ target
  demand : AtomDemand
  formation : Prop

namespace DeclTyping

/-- Object declaration without initializer. -/
def objectNoInit {Γ : TypeEnv} {τ : CppType} {x : Ident}
    (fresh : TypeEnv.Fresh Γ x)
    (_objectType : ObjectType τ) :
    DeclTyping Γ (.object τ x .noInit) where
  target := TypeEnv.bind Γ x (.object τ)
  envEffect := TypeEnvEffect.bindObject fresh
  demand := AtomDemand.declRaw []
  formation := ObjectType τ

/-- Object declaration with an initializer. -/
def objectInit {Γ : TypeEnv} {τ : CppType} {x : Ident} {e : ValExpr}
    (fresh : TypeEnv.Fresh Γ x)
    (_objectType : ObjectType τ)
    (init : InitTyping Γ (.value e) τ) :
    DeclTyping Γ (.object τ x (.value e)) where
  target := TypeEnv.bind Γ x (.object τ)
  envEffect := TypeEnvEffect.bindObject fresh
  demand := AtomDemand.declWithInit [] init.demand
  formation := ObjectType τ

/-- Reference declaration from an already typed target place. -/
def ref {Γ : TypeEnv} {τ : CppType} {x : Ident} {target : PlaceExpr}
    (fresh : TypeEnv.Fresh Γ x)
    (targetTyping : PlaceTyping Γ target)
    (_compatible : targetTyping.ty = τ) :
    DeclTyping Γ (.ref τ x target) where
  target := TypeEnv.bind Γ x (.ref τ)
  envEffect := TypeEnvEffect.bindRef fresh
  demand := AtomDemand.declRef [] targetTyping.demand
  formation := targetTyping.ty = τ

end DeclTyping

/-- Micro typing certificate for an expression statement. -/
structure ExprStmtTyping (Γ : TypeEnv) (s : CppExprStmt) : Type where
  expr : ValExpr
  exprTyping : ExprTyping Γ expr
  isDiscard : s = .discard expr

namespace ExprStmtTyping

/-- Build a discarded-expression statement from a typed expression. -/
def discard {Γ : TypeEnv} {e : ValExpr}
    (h : ExprTyping Γ e) : ExprStmtTyping Γ (.discard e) where
  expr := e
  exprTyping := h
  isDiscard := rfl

/-- Demand generated by an expression statement. -/
def demand {Γ : TypeEnv} {s : CppExprStmt}
    (h : ExprStmtTyping Γ s) : AtomDemand :=
  AtomDemand.exprStmt h.exprTyping.demand

end ExprStmtTyping

/-- Micro typing certificate for a simple assignment. -/
structure AssignTyping (Γ : TypeEnv) (a : CppAssign) : Type where
  place : PlaceExpr
  expr : ValExpr
  placeTyping : PlaceTyping Γ place
  exprTyping : ExprTyping Γ expr
  isSimple : a = .simple place expr
  compatible : exprTyping.ty = placeTyping.ty

namespace AssignTyping

/-- Build a simple assignment certificate. -/
def simple {Γ : TypeEnv} {p : PlaceExpr} {e : ValExpr}
    (hp : PlaceTyping Γ p) (he : ExprTyping Γ e)
    (compatible : he.ty = hp.ty) : AssignTyping Γ (.simple p e) where
  place := p
  expr := e
  placeTyping := hp
  exprTyping := he
  isSimple := rfl
  compatible := compatible

/-- Demand generated by an assignment. -/
def demand {Γ : TypeEnv} {a : CppAssign}
    (h : AssignTyping Γ a) : AtomDemand :=
  AtomDemand.assign h.placeTyping.writeDemand h.exprTyping.demand

end AssignTyping

/-- Micro typing for primitive ControlPlan atoms. -/
inductive AtomTyping (Γ : TypeEnv) (κ : ControlContext) : ControlAtom → Type where
  | skip : AtomTyping Γ κ .skip
  | exprStmt {s : CppExprStmt}
      (h : ExprStmtTyping Γ s) : AtomTyping Γ κ (.exprStmt s)
  | assign {a : CppAssign}
      (h : AssignTyping Γ a) : AtomTyping Γ κ (.assign a)
  | decl {d : CppDecl}
      (h : DeclTyping Γ d) : AtomTyping Γ κ (.decl d)
  | jump {j : CppJump}
      (h : JumpTyping κ j) : AtomTyping Γ κ (.jump j)

namespace AtomTyping

/-- Demand generated by a typed primitive atom. -/
def demand {Γ : TypeEnv} {κ : ControlContext} {a : ControlAtom} :
    AtomTyping Γ κ a → AtomDemand
  | .skip => AtomDemand.skip
  | .exprStmt h => h.demand
  | .assign h => h.demand
  | .decl h => h.demand
  | .jump h => h.demand

end AtomTyping

end Cpp4
