import CppFormalization.Cpp4.Typing.Micro.Place

/-!
# CppFormalization.Cpp4.Typing.Micro.Expr

Micro typing certificates for value expressions.

This layer records the expression type, generated `ExprDemand`, and evidence for
its formation side condition.  Call-specific construction is added in
`Typing.Micro.CallArgs`, so expression typing can remain below callable-argument
typing without an import cycle.
-/

namespace Cpp4

/-- A typed value-expression certificate.

`formation` states the C++ typing side condition; `evidence` proves it. -/
structure ExprTyping (Γ : TypeEnv) (e : ValExpr) : Type where
  ty : CppType
  demand : ExprDemand
  formation : Prop
  evidence : formation

namespace ExprTyping

/-- Boolean literal typing. -/
def litBool {Γ : TypeEnv} (b : Bool) : ExprTyping Γ (.litBool b) where
  ty := .base .bool
  demand := ExprDemand.literal
  formation := True
  evidence := trivial

/-- Integer literal typing. -/
def litInt {Γ : TypeEnv} (n : Int) : ExprTyping Γ (.litInt n) where
  ty := .base .int
  demand := ExprDemand.literal
  formation := True
  evidence := trivial

/-- Null pointer literal.  The pointee type is supplied by contextual typing. -/
def nullPtrAs {Γ : TypeEnv} (τ : CppType) : ExprTyping Γ .nullPtr where
  ty := .ptr τ
  demand := ExprDemand.literal
  formation := True
  evidence := trivial

/-- Load from a typed place. -/
def load {Γ : TypeEnv} {p : PlaceExpr}
    (hp : PlaceTyping Γ p) : ExprTyping Γ (.load p) where
  ty := hp.ty
  demand := ExprDemand.load hp.readDemand
  formation := hp.formation
  evidence := hp.evidence

/-- Address-of a typed place. -/
def addrOf {Γ : TypeEnv} {p : PlaceExpr}
    (hp : PlaceTyping Γ p) : ExprTyping Γ (.addrOf p) where
  ty := .ptr hp.ty
  demand := ExprDemand.addrOf hp.addressDemand
  formation := hp.formation
  evidence := hp.evidence

/-- Integer addition. -/
def addInt {Γ : TypeEnv} {lhs rhs : ValExpr}
    (hl : ExprTyping Γ lhs) (hr : ExprTyping Γ rhs)
    (hlTy : hl.ty = .base .int) (hrTy : hr.ty = .base .int) :
    ExprTyping Γ (.add lhs rhs) where
  ty := .base .int
  demand := ExprDemand.binary hl.demand hr.demand
  formation := hl.formation ∧ hr.formation ∧ hl.ty = .base .int ∧ hr.ty = .base .int
  evidence := And.intro hl.evidence (And.intro hr.evidence (And.intro hlTy hrTy))

/-- Integer subtraction. -/
def subInt {Γ : TypeEnv} {lhs rhs : ValExpr}
    (hl : ExprTyping Γ lhs) (hr : ExprTyping Γ rhs)
    (hlTy : hl.ty = .base .int) (hrTy : hr.ty = .base .int) :
    ExprTyping Γ (.sub lhs rhs) where
  ty := .base .int
  demand := ExprDemand.binary hl.demand hr.demand
  formation := hl.formation ∧ hr.formation ∧ hl.ty = .base .int ∧ hr.ty = .base .int
  evidence := And.intro hl.evidence (And.intro hr.evidence (And.intro hlTy hrTy))

/-- Integer multiplication. -/
def mulInt {Γ : TypeEnv} {lhs rhs : ValExpr}
    (hl : ExprTyping Γ lhs) (hr : ExprTyping Γ rhs)
    (hlTy : hl.ty = .base .int) (hrTy : hr.ty = .base .int) :
    ExprTyping Γ (.mul lhs rhs) where
  ty := .base .int
  demand := ExprDemand.binary hl.demand hr.demand
  formation := hl.formation ∧ hr.formation ∧ hl.ty = .base .int ∧ hr.ty = .base .int
  evidence := And.intro hl.evidence (And.intro hr.evidence (And.intro hlTy hrTy))

/-- Equality comparison between two expressions of the same type. -/
def eqSame {Γ : TypeEnv} {lhs rhs : ValExpr}
    (hl : ExprTyping Γ lhs) (hr : ExprTyping Γ rhs)
    (sameTy : hl.ty = hr.ty) : ExprTyping Γ (.eq lhs rhs) where
  ty := .base .bool
  demand := ExprDemand.binary hl.demand hr.demand
  formation := hl.formation ∧ hr.formation ∧ hl.ty = hr.ty
  evidence := And.intro hl.evidence (And.intro hr.evidence sameTy)

/-- Integer less-than comparison. -/
def ltInt {Γ : TypeEnv} {lhs rhs : ValExpr}
    (hl : ExprTyping Γ lhs) (hr : ExprTyping Γ rhs)
    (hlTy : hl.ty = .base .int) (hrTy : hr.ty = .base .int) :
    ExprTyping Γ (.lt lhs rhs) where
  ty := .base .bool
  demand := ExprDemand.binary hl.demand hr.demand
  formation := hl.formation ∧ hr.formation ∧ hl.ty = .base .int ∧ hr.ty = .base .int
  evidence := And.intro hl.evidence (And.intro hr.evidence (And.intro hlTy hrTy))

/-- Boolean negation. -/
def notBool {Γ : TypeEnv} {e : ValExpr}
    (h : ExprTyping Γ e) (hTy : h.ty = .base .bool) :
    ExprTyping Γ (.not e) where
  ty := .base .bool
  demand := ExprDemand.unary h.demand
  formation := h.formation ∧ h.ty = .base .bool
  evidence := And.intro h.evidence hTy

end ExprTyping

/-- Micro typing for boolean-like control conditions. -/
structure CondTyping (Γ : TypeEnv) (c : CppCond) : Type where
  expr : ValExpr
  exprTyping : ExprTyping Γ expr
  isCondition : c = .expr expr
  boolLike : exprTyping.ty = .base .bool

namespace CondTyping

/-- Build a condition typing certificate from a typed boolean expression. -/
def ofBoolExpr {Γ : TypeEnv} {e : ValExpr}
    (h : ExprTyping Γ e) (hTy : h.ty = .base .bool) :
    CondTyping Γ (.expr e) where
  expr := e
  exprTyping := h
  isCondition := rfl
  boolLike := hTy

/-- Demand generated by a typed condition. -/
def demand {Γ : TypeEnv} {c : CppCond} (h : CondTyping Γ c) : ExprDemand :=
  h.exprTyping.demand

end CondTyping

end Cpp4
