import CppFormalization.Cpp4.Typing.Micro.Expr
import CppFormalization.Cpp4.Resource.Demand.Switch

/-!
# CppFormalization.Cpp4.Typing.Micro.Switch

Micro typing for switch conditions and switch labels.

The body of each switch arm is a statement/block judgment, so this file only
records the condition/label side and the control-context transition for arm
bodies.  Demand for switch suffixes is supplied later by Plan/Surface judgment
layers from typed arm bodies.
-/

namespace Cpp4

/-- Micro typing for a C++ switch condition.  Cpp4 starts with normalized integer
switch labels, so the first condition discipline is integer-like. -/
structure SwitchCondTyping (Γ : TypeEnv) (c : CppSwitchCond) : Type where
  expr : ValExpr
  exprTyping : ExprTyping Γ expr
  isSwitchCond : c = .expr expr
  integral : exprTyping.ty = .base .int

namespace SwitchCondTyping

/-- Build a switch condition from a typed integer expression. -/
def ofIntExpr {Γ : TypeEnv} {e : ValExpr}
    (h : ExprTyping Γ e) (hTy : h.ty = .base .int) :
    SwitchCondTyping Γ (.expr e) where
  expr := e
  exprTyping := h
  isSwitchCond := rfl
  integral := hTy

/-- Demand generated by a typed switch condition. -/
def demand {Γ : TypeEnv} {c : CppSwitchCond}
    (h : SwitchCondTyping Γ c) : ExprDemand :=
  h.exprTyping.demand

end SwitchCondTyping

/-- Micro typing for normalized switch labels. -/
inductive SwitchLabelTyping : SwitchLabel → Type where
  | caseInt (n : Int) : SwitchLabelTyping (.caseInt n)
  | defaultLabel : SwitchLabelTyping .defaultLabel

namespace SwitchLabelTyping

/-- A switch label does not itself require runtime resources. -/
def demand {l : SwitchLabel} (h : SwitchLabelTyping l) : SwitchArmDemand := by
  cases h <;> exact { demands := [] }

end SwitchLabelTyping

/-- Header-level typing for a surface switch arm.  The arm body is deliberately
left for statement/block judgment. -/
structure SwitchArmHeaderTyping (arm : SwitchArm) : Type where
  labelTyping : SwitchLabelTyping arm.label

/-- Header-level typing for a ControlPlan switch arm. -/
structure SwitchPlanArmHeaderTyping (arm : SwitchPlanArm) : Type where
  labelTyping : SwitchLabelTyping arm.label

namespace SwitchArmHeaderTyping

/-- Demand contributed by a surface arm header. -/
def demand {arm : SwitchArm} (h : SwitchArmHeaderTyping arm) : SwitchArmDemand :=
  h.labelTyping.demand

end SwitchArmHeaderTyping

namespace SwitchPlanArmHeaderTyping

/-- Demand contributed by a plan arm header. -/
def demand {arm : SwitchPlanArm} (h : SwitchPlanArmHeaderTyping arm) : SwitchArmDemand :=
  h.labelTyping.demand

end SwitchPlanArmHeaderTyping

/-- Control context used inside a switch arm body. -/
def switchArmControlContext (κ : ControlContext) : ControlContext :=
  ControlContext.enterSwitch κ

end Cpp4
