import CppFormalization.Cpp2.Static.StructuralAdmission.LoopBody.All
import CppFormalization.Cpp2.Static.StructuralAdmission.BodyStructuralBoundary
import CppFormalization.Cpp2.Static.StructuralAdmission.BodyStructuralBoundaryLite
