import CppFormalization.Cpp2.Closure.Transitions.DeclareRef.Shape
import CppFormalization.Cpp2.Closure.Transitions.DeclareRef.RuntimeTransport
import CppFormalization.Cpp2.Closure.Transitions.DeclareRef.Realizers
import CppFormalization.Cpp2.Closure.Transitions.DeclareRef.Ownership
import CppFormalization.Cpp2.Closure.Transitions.DeclareRef.Preservation
