import CppFormalization.Cpp2.Closure.Transitions.DeclareObject.Shape
import CppFormalization.Cpp2.Closure.Transitions.Major.DeclareObjectTransport
import CppFormalization.Cpp2.Closure.Transitions.Major.DeclareObjectOwnership
import CppFormalization.Cpp2.Closure.Transitions.Major.DeclareObjectRealizers
import CppFormalization.Cpp2.Closure.Transitions.Major.DeclareObjectDecomposition
