import CppFormalization.Cpp2.Static.Facts.Control.BodyClosureBoundaryControlExclusionCI
import CppFormalization.Cpp2.Static.Facts.Control.BodyReadyControlExclusionCI
import CppFormalization.Cpp2.Static.Facts.Control.TypingCINormalExclusion
import CppFormalization.Cpp2.Static.Facts.Control.TypingCISeparation
