import CppFormalization.Cpp4.Resource.Certification.Provider
import CppFormalization.Cpp4.Resource.Transport.All

/-!
# CppFormalization.Cpp4.Resource.Certification.Transport

Bridges from noninterference certificates to the existing `Resource.Transport`
providers.

The point of this file is migration: raw transport structures remain available,
but can now be generated by theorem from the certification pipeline rather than
passed around as opaque assumptions.
-/

namespace Cpp4

/-- Generate a raw statement transport from noninterference. -/
def stmtTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : StmtDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    StmtTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw block transport from noninterference. -/
def blockTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : BlockDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    BlockTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw expression transport from noninterference. -/
def exprTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : ExprDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    ExprTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw call transport from noninterference. -/
def callTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : CallDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    CallTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw ControlPlan transport from noninterference. -/
def planTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : PlanDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    PlanTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw plan-block transport from noninterference. -/
def planBlockTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : PlanBlockDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    PlanBlockTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw loop transport from noninterference. -/
def loopTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : LoopDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    LoopTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw switch transport from noninterference. -/
def switchTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : SwitchDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    SwitchTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw surface-statement transport from noninterference. -/
def surfaceStmtTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : SurfaceStmtDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    SurfaceStmtTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

/-- Generate a raw surface-block transport from noninterference. -/
def surfaceBlockTransport_of_noninterference
    {χ χ' : DemandContext} {σ σ' : State} {eff : ResourceEffect}
    {before after : SurfaceBlockDemand}
    (h : NoninterferenceCertificate χ χ' σ σ' eff before.demands after.demands) :
    SurfaceBlockTransport χ χ' σ σ' eff before after where
  preserves := h.toEffectPreservesDemand

end Cpp4
