import CppFormalization.Cpp2.Legacy.Foundation.BodyClosureBoundaryLite
import CppFormalization.Cpp2.Legacy.Foundation.LoopBodyBoundaryCompatibility
import CppFormalization.Cpp2.Legacy.Foundation.WhileEntryBoundaryCompatibilityCI
